# Generated by Django 2.0.4 on 2018-04-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoproject', '0002_appointment_forfait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
